"""
Final test: Verify NIRF collector will find IIT Bombay 2025 PDF
"""
import asyncio
import aiohttp

async def test_drupal_probe():
    """Test direct probing of the IIT Bombay NIRF PDF"""
    
    target_url = "https://www.iitb.ac.in/sites/www.iitb.ac.in/files/2025-02/NIRF_IITBombay_2025_Overall_Category_0.pdf"
    
    print(f"Testing direct access to IIT Bombay NIRF PDF:")
    print(f"  {target_url}\n")
    
    timeout = aiohttp.ClientTimeout(total=15)
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
    
    try:
        async with aiohttp.ClientSession(timeout=timeout, headers=headers) as session:
            # Try HEAD request first (faster)
            print("Testing with HEAD request...")
            async with session.head(target_url, ssl=False, allow_redirects=True) as response:
                print(f"  Status: {response.status}")
                if response.status == 200:
                    print(f"  ✓✓✓ SUCCESS! PDF is accessible")
                    print(f"  Content-Type: {response.headers.get('Content-Type', 'N/A')}")
                    print(f"  Content-Length: {response.headers.get('Content-Length', 'N/A')} bytes")
                    return True
                else:
                    print(f"  ✗ PDF not accessible (status {response.status})")
                    return False
                    
    except Exception as e:
        print(f"  ✗ Error accessing PDF: {e}")
        return False

async def test_pattern_generation():
    """Test that our pattern will be generated"""
    from nirf_collector import NIRFCollector
    
    collector = NIRFCollector()
    domain = "www.iitb.ac.in"
    
    print(f"\n{'='*80}")
    print(f"Testing pattern generation for {domain}:")
    print(f"{'='*80}\n")
    
    patterns = collector._generate_drupal_nirf_patterns(domain)
    
    target_path = "/sites/www.iitb.ac.in/files/2025-02/NIRF_IITBombay_2025_Overall_Category_0.pdf"
    
    # Build full URL for each pattern
    base_url = f"https://{domain}"
    
    found = False
    for pattern in patterns:
        if pattern == target_path:
            print(f"✓✓✓ SUCCESS! Target pattern IS in generated list:")
            print(f"    {pattern}\n")
            found = True
            break
    
    if not found:
        print(f"✗ Target pattern NOT found")
        print(f"\nTarget: {target_path}")
        print(f"\nClosest 2025-02 matches:")
        for pattern in patterns:
            if '2025-02' in pattern and 'Overall' in pattern:
                print(f"  {pattern}")
    
    print(f"\nTotal patterns generated: {len(patterns)}")
    
    return found

async def main():
    """Run all tests"""
    
    print(f"{'='*80}")
    print(f"IIT BOMBAY NIRF 2025 PDF DISCOVERY TEST")
    print(f"{'='*80}\n")
    
    # Test 1: Can we access the PDF directly?
    pdf_accessible = await test_drupal_probe()
    
    # Test 2: Will our pattern generation find it?
    pattern_found = await test_pattern_generation()
    
    # Summary
    print(f"\n{'='*80}")
    print(f"TEST SUMMARY:")
    print(f"{'='*80}")
    print(f"1. PDF is accessible via direct URL: {'✓ YES' if pdf_accessible else '✗ NO'}")
    print(f"2. Pattern is generated by collector: {'✓ YES' if pattern_found else '✗ NO'}")
    
    if pdf_accessible and pattern_found:
        print(f"\n✓✓✓ COMPLETE SUCCESS!")
        print(f"The NIRF collector WILL NOW find the IIT Bombay 2025 PDF")
    elif pattern_found:
        print(f"\n⚠ Pattern is generated but PDF may not be accessible")
        print(f"   (Could be temporary network issue)")
    else:
        print(f"\n✗ Pattern generation needs further refinement")

if __name__ == "__main__":
    asyncio.run(main())
